### ISSUE TITLE
Can I run multi-gpu pretraining?

### ISSUE THREAD

**Issue by alex27594** [yutkin/BiMorph-Tensorflow#2]
Hello, I am trying to get my hands dirty with training your solution from scratch etc. and I have 4 gpus at my disposal. I want to see if there is a way that I can distribute the training across all of them. Thanks.

**Comment by kefirski** [comment]
We are planning to add multi-gpu/multi-node training in the future. Current implementation implies training on single gpu only

**Comment by alex27594** [comment]
Nice to hear, cool job guys!
